Bates_Energy_Website/Bates_Energy/urls.py
from django.urls import path

from . import views

app_name = "Bates_Energy"
urlpatterns = [
    path('', views.index, name='index'),
    path('import_data', views.import_data, name='import_data'),
    path('processed_data/<names>', views.processed_data, name='processed_data'),
]

Bates_Energy_Website/Bates_Energy_Website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('Bates_Energy/', include('Bates_Energy.urls')),
    path('admin/', admin.site.urls),
]

Bates_Energy_Website/Bates_Energy/models.py
from django.db import models


class Observation(models.Model):
    building = models.CharField(max_length=150, unique=False, null=True)
    date_time = models.DateTimeField(null=True, blank=True)
    quantity = models.FloatField(unique=False, null=True)
    string_time = models.CharField(max_length=20, unique=False, null=True, blank=True)

    class Meta:
        ordering = ['date_time']

    def __str__(self):
        return str(self.building)

Bates_Energy_Website/Bates_Energy/forms.py
from django import forms
from .models import *
import pandas as pd
import numpy as np
from fuzzywuzzy import process
from django.forms import ClearableFileInput


class DataInput(forms.Form):
    files = forms.FileField(widget=ClearableFileInput(attrs={'multiple': True}))

    def rename_columns(self, data, column_names):
        subs = {}
        for column in data:
            best_guess = process.extractOne(column, column_names)
            if 75 < best_guess[1] < 100:
                subs[column] = best_guess[0]
        data.rename(columns=subs, inplace=True)

    def remove_out_of_tolerance(self, x, max_poss, min_poss):
        if x > max_poss or x <= min_poss:
            return np.nan
        else:
            return x

    def extrapolate(self, data, column):
        length = len(data.index)
        for i, obs in enumerate(data[column]):
            if np.isnan(obs) and not np.isnan(data[column][i - 1]):
                j = i + 1
                while j < length and np.isnan(data[column][j]):
                    j += 1
                if j < length:
                    avg = (data[column][i - 1] + data[column][j]) / 2
                    data[column][i:j] = [avg for _ in range(i, j)]

    def save(self, energy):
        building_names = ['Adams', 'Bertram', 'Carnegie', 'Chapel', 'Chase', 'Pettigrew', 'Rzasa', 'Libbey', 'Page',
                          'Rand', 'Schaeffer', 'Lane', 'LaddLibrary', 'Hathorn', 'Parker', 'Cheney', 'Dana',
                          'Underhill', 'UnderhillIce', 'Olin', 'Pettengill']
        tolerances = {'Adams': 50, 'Bertram': 50, 'Carnegie': 800, 'Chapel': 20, 'Chase': 300, 'Pettigrew': 100,
                      'Rzasa': 100, 'Libbey': 50, 'Page': 50, 'Rand': 50, 'Schaeffer': 50, 'Lane': 300,
                      'LaddLibrary': 300, 'Hathorn': 50, 'Parker': 50, 'Cheney': 50, 'Dana': 300, 'Underhill': 1000,
                      'UnderhillIce': 1000, 'Olin': 200, 'Pettengill': 400}

        # energy = pd.read_csv(self.cleaned_data["file"], index_col=0)
        energy.rename(columns=lambda x: x.split(' (')[0], inplace=True)

        self.rename_columns(energy, building_names)

        for building in energy:
            tolerance = tolerances[building]
            energy[building] = energy[building].apply(self.remove_out_of_tolerance, args=(tolerance, 0))
            self.extrapolate(energy, building)

        energy.index = pd.to_datetime(energy.index, errors='ignore', utc=True)
        for building in energy:
            observations = [
                Observation(
                    building=building,
                    quantity=obs,
                    date_time=energy.index[i],
                    string_time=energy.index[i].strftime('%Y-%m-%d-%H-%M')
                ) for i, obs in enumerate(energy[building])
            ]
            length = len(observations)
            start = 0
            end = start + 999

            if length % 999 == 0:
                cycles = length // 999
            else:
                cycles = (length // 999) + 1

            for cycle in range(cycles):
                Observation.objects.bulk_create(observations[start:min(end, length)])
                start, end = min(end, length), min(end+999, length)

    # def save(self):
    #     for file in self.cleaned_data["file"]:
    #         energy = pd.read_csv(file, index_col=0)
    #         self.upload(energy)
    #

Bates_Energy_Website/Bates_Energy/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse
from .forms import *
import datetime
from django.contrib.admin.views.decorators import staff_member_required
import pandas as pd




def index(request):
    return render(request, 'Bates_Energy/index2.html')


# def processed_data(request, names):
#
#     buildings_data_dict = {}
#     buildings_data = pd.DataFrame()
#     names = names.split(',')
#
#     if names[0] == 'date':
#         for i, date in enumerate(names[2::]):
#             if i == 0:
#                 buildings_data_dict['Time'] = pd.DataFrame({'Time':[obs.Time.strftime('%Y-%m-%d-%H-%M') for obs in Observation.objects.filter(
#                     building=names[1],
#                     Time__gt=datetime.datetime(int(date), 1, 1, 0, 0),
#                     Time__lt=datetime.datetime(int(date) + 1, 1, 1, 0, 0)
#                 )]})
#             buildings_data_dict[date] = pd.DataFrame({date: [obs.Quantity for obs in Observation.objects.filter(
#                 building=names[1],
#                 Time__gt=datetime.datetime(int(date), 1, 1, 0, 0),
#                 Time__lt=datetime.datetime(int(date)+1, 1, 1, 0, 0)
#             )]})
#         buildings_data = pd.concat([buildings_data_dict[col] for col in buildings_data_dict], axis=1)
#
#     else:
#         for i, name in enumerate(names):
#             if i == 0:
#                 buildings_data_dict['Time'] = pd.DataFrame({'Time':[obs.Time.strftime('%Y-%m-%d-%H-%M') for obs in Observation.objects.filter(building=name)]})
#             buildings_data_dict[name] = pd.DataFrame({name: [obs.Quantity for obs in Observation.objects.filter(building=name)]})
#         buildings_data = pd.concat([buildings_data_dict[col] for col in buildings_data_dict], axis=1)
#
#     buildings_data = buildings_data.to_csv(index=False)
#     return HttpResponse(buildings_data, content_type="text/csv")
#

def processed_data(request, names):

    buildings_data_dict = {}
    buildings_data = pd.DataFrame()
    names = names.split(',')

    if names[0] == 'date':
        for i, date in enumerate(names[2::]):
            if i == 0:
                buildings_data['Time'] = Observation.objects.filter(
                    building=names[1],
                    date_time__gt=datetime.datetime(int(date), 1, 1, 0, 0),
                    date_time__lt=datetime.datetime(int(date) + 1, 1, 1, 0, 0)
                ).values_list('string_time', flat=True)
            buildings_data[date] = Observation.objects.filter(
                building=names[1],
                date_time__gt=datetime.datetime(int(date), 1, 1, 0, 0),
                date_time__lt=datetime.datetime(int(date)+1, 1, 1, 0, 0)
            ).values_list('quantity', flat=True)

    else:
        for i, name in enumerate(names):
            if i == 0:
                buildings_data['Time'] = Observation.objects.filter(building=name).values_list('string_time', flat=True)
            buildings_data[name] = Observation.objects.filter(building=name).values_list('quantity', flat=True)
    buildings_data_df = pd.concat([buildings_data[col] for col in buildings_data], axis=1)
    buildings_data_csv = buildings_data_df.to_csv(index=False)
    return HttpResponse(buildings_data_csv, content_type="text/csv")


staff_member_required


def import_data(request):
    if request.method == "POST":
        # form = DataInput(request.POST, request.FILES)
        # # TODO: redefine is_valid() to validate CSV
        # if form.is_valid():
        #     form.save()
        files = request.FILES.getlist('files')
        for f in files:
            energy = pd.read_csv(f, index_col=0)
            DataInput().save(energy)
        return HttpResponseRedirect(reverse('Bates_Energy:index'))
    else:
        if Observation.objects.first():
            oldest_date = Observation.objects.first().date_time
            latest_date = Observation.objects.last().date_time
        else:
            oldest_date, latest_date = 'No available data', 'No available data'
        form = DataInput()
        context = {"latest_date": latest_date, "oldest_date": oldest_date, "csv_upload_form": form}
        return render(request, "Bates_Energy/imported.html", context)

Bates_Energy_Website/Bates_Energy/templates/Bates_Energy/imported.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'Bates_Energy/css/index.css' %}?{% now 'U' %}"/>
    <title>import Energy Data</title>
</head>
<body>

    <div class="instructions">
      <ul>
        <li>Oldest record: {{oldest_date}}</li>
        <li>Latest record: {{latest_date}}</li>
    </ul>
    </div>
    <div class="instructions" style="margin-top:10px">
<!--        <form action="{% url 'Bates_Energy:import_data' %}" method="post" enctype="multipart/form-data">-->
<!--            {% csrf_token %}-->
<!--          <label for="files">Select files:</label>-->
<!--          <input type="file" id="files" name="files" multiple><br><br>-->
<!--          <input type="submit">-->
<!--        </form>-->
        <form  action="{% url 'Bates_Energy:import_data' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ csv_upload_form }}
                <input type="submit" value="Upload">
        </form>
    </div>
</body>
</html>

Bates_Energy_Website/Bates_Energy/templates/Bates_Energy/index.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'Bates_Energy/css/index.css' %}?{% now 'U' %}"/>
    <title>Bates Eco Site</title>

    <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="https://d3js.org/d3-dsv.v1.min.js"></script>

<!--    <script defer src="/__/firebase/7.9.1/firebase-app.js"></script>-->
<!--    <script defer src="/__/firebase/init.js"></script>-->
  </head>
  <body>
    <!-- Welcome to the eco reps site. Here is just some sample plotting that we will expand on...<br><br>- Leo and Fahim<br><br> -->
    <!-- <div class="chart"></div> -->
<!--    <img src="bobcat.png" alt="Bobcat">-->
    <h1 class="header">
      Bates Energy Consumption Profile
    </h1>
    <div class="instructions">
      <ul>
        <li>Select a building name to view its energy consumption profile</li>
        <li>Make box selection on the bottom plot to view focused time-period on the top plot</li>
        <li>Hover mouse over the top plot and use mouse pad to zoom in/out and drag focused time-period</li>
      </ul>
    </div>
    <div id="vis-container"></div>
      <script type="module" src ="{% static 'Bates_Energy/js/main.js' %}?{% now 'U' %}"></script>
    <!--<script type="module" src="main.js"></script>-->
    <!-- <script type="module" src="get_data.js"></script> -->
  {{url}}
  </body>
</html>

Bates_Energy_Website/Bates_Energy/templates/Bates_Energy/index2.html
<!DOCTYPE html>
<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'Bates_Energy/css/index.css' %}?{% now 'U' %}"/>
    <title>Bates Eco Site</title>

    <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3-legend/2.25.6/d3-legend.min.js"></script>




    <script src="https://d3js.org/d3-dsv.v1.min.js"></script>

<!--    <script defer src="/__/firebase/7.9.1/firebase-app.js"></script>-->
<!--    <script defer src="/__/firebase/init.js"></script>-->
    <style>

    svg {
    font: 10px sans-serif;
    }


    .axis path,
    .axis line {
    fill: none;
    stroke: #000;
    shape-rendering: crispEdges;
    }

    .y.axis path {
    fill: none;
    stroke: #000;
    shape-rendering: crispEdges;
    }

    .brush .extent {
    stroke: #fff;
    fill-opacity: .125;
    shape-rendering: crispEdges;
    }

    .line {
    fill: none;
    }

    </style>

  </head>
  <body>
    <!-- Welcome to the eco reps site. Here is just some sample plotting that we will expand on...<br><br>- Leo and Fahim<br><br> -->
    <!-- <div class="chart"></div> -->
<!--    <img src="bobcat.png" alt="Bobcat">-->
    <h1 class="header">
      Bates Energy Consumption Profile
    </h1>
    <div class="instructions">
      <ul>
        <li>Select multiple building names to view their energy consumption profile</li>
        <li>Make box selection on the bottom plot to view focused time-period on the top plot</li>

      </ul>
    </div>
    <form method="post" class="instructions" style="margin-top:10px">
        <input checked type="radio" id='compare buildings' name="compare" value="buildings">
        <label for="compare buildings">Compare Buildings</label><br>
        <input type="radio" id='compare years' name="compare" value="years">
        <label for="compare years">Compare Years</label><br>
    </form>
  <div id="vis-container"></div>

      <script type="module" src ="{% static 'Bates_Energy/js/main2.js' %}?{% now 'U' %}"></script>
  </body>
</html>